# Global configuration
seed: 42
device: "cuda"

data:
  imaging_root: "/path/to/tcia_ct_or_mri"
  genomics_root: "/path/to/tcga"
  clinical_csv: "/path/to/clinical.csv"
  cache_dir: "./cache"

ssl_pretrain:
  batch_size: 4
  epochs: 100
  lr: 1e-4
  temperature: 0.2
  image_size: [96, 96, 96]  # 3D patches (D,H,W)
  augment:
    rotate_deg: 15
    flip_prob: 0.5
    intensity_jitter: 0.1

fusion_train:
  batch_size: 2
  epochs: 60
  lr: 3e-4
  weight_decay: 1e-4
  cox_lambda: 1.0
  class_weights: [1.0, 1.0, 1.0, 1.0]  # adjust per class
